### ISSUE TITLE
Nan outputs

### ISSUE THREAD

**Issue by nfvalderrama** [soumickmj/DS6#1]
Hi! I am trying to use your code with my own dataset, but I seem to have a problem on the training as it is not converging and the outputs are Nan. Maybe having some pretrained weights would help. Is it possible you could share your trained weights?

**Comment by soumickmj** [comment]
Hi!
It's nearly 2-years too late and my response might be completely useless, but the weights were not made public. Here they are (just in case you still need them): https://huggingface.co/collections/soumickmj/ds6-66d623af4a69536bcaf3c377

The base model without deformation must first be trained, before fine-tuning the same trained model with deformation for DS6.
